# Generated by Django 3.2.11 on 2022-01-04 14:53

import uuid
from decimal import Decimal

import django.db.models.deletion
import djmoney.models.fields
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=5000)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=140)),
                ('description', models.TextField(max_length=5000)),
                ('link', models.URLField()),
                ('product_img', models.ImageField(upload_to='deals_photo')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('current_price_currency',
                 djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('USD', 'USD $'), ('PLN', 'zł')],
                                                     default='PLN', editable=False, max_length=3)),
                ('current_price',
                 djmoney.models.fields.MoneyField(decimal_places=2, default_currency='PLN', max_digits=19)),
                ('historical_price_currency',
                 djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('USD', 'USD $'), ('PLN', 'zł')],
                                                     default='PLN', editable=False, max_length=3)),
                ('historical_price',
                 djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'),
                                                  default_currency='PLN', max_digits=19)),
                ('delivery_cost_currency',
                 djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('USD', 'USD $'), ('PLN', 'zł')],
                                                     default='PLN', editable=False, max_length=3)),
                ('delivery_cost',
                 djmoney.models.fields.MoneyField(decimal_places=2, default_currency='PLN', max_digits=19)),
                ('valid_till', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('promo_code', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('vote_up', models.IntegerField(default=0)),
                ('vote_down', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                               to='deals.category')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vote_value', models.IntegerField(choices=[(1, 'Plus'), (-1, 'Minus'), (0, 'Neutral')])),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.deal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.deal')),
            ],
        ),
    ]
