# Generated by Django 3.2.10 on 2021-12-20 14:35

import uuid
from decimal import Decimal

import django.db.models.deletion
import django_quill.fields
import djmoney.models.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('description', django_quill.fields.QuillField(max_length=5000)),
                ('link', models.URLField()),
                ('product_img', models.ImageField(upload_to='deals_photo')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('current_price_currency',
                 djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('USD', 'USD $'), ('PLN', 'zł')],
                                                     default='PLN', editable=False, max_length=3)),
                ('current_price',
                 djmoney.models.fields.MoneyField(decimal_places=2, default_currency='PLN', max_digits=19)),
                ('historical_price_currency',
                 djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('USD', 'USD $'), ('PLN', 'zł')],
                                                     default='PLN', editable=False, max_length=3)),
                ('historical_price',
                 djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'),
                                                  default_currency='PLN', max_digits=19)),
                ('delivery_cost_currency',
                 djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('USD', 'USD $'), ('PLN', 'zł')],
                                                     default='PLN', editable=False, max_length=3)),
                ('delivery_cost',
                 djmoney.models.fields.MoneyField(decimal_places=2, default_currency='PLN', max_digits=19)),
                ('valid_till', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('promo_code', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('vote_up', models.IntegerField(default=0)),
                ('vote_down', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vote_value', models.IntegerField(choices=[(1, 'Plus'), (-1, 'Minus'), (0, 'Neutral')])),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.deal')),
            ],
        ),
    ]
