# Generated by Django 3.2.9 on 2021-11-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.CharField(default='test', max_length=500),
            preserve_default=False,
        ),
    ]
