# Generated by Django 3.2.10 on 2021-12-22 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deals.category'),
        ),
    ]
