# Generated by Django 3.2.11 on 2022-01-12 21:53

from decimal import Decimal

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('deals', '0002_auto_20220109_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='current_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='PLN',
                                                   max_digits=19),
        ),
        migrations.AlterField(
            model_name='deal',
            name='delivery_cost',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'),
                                                   default_currency='PLN', max_digits=19, null=True),
        ),
    ]
