# Generated by Django 3.2.9 on 2021-11-23 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_comment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deal',
            old_name='pub_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='deal',
            old_name='modified',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
