# Generated by Django 3.2.10 on 2021-12-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='name',
            field=models.CharField(db_index=True, max_length=140),
        ),
    ]
