# Generated by Django 3.2.9 on 2021-11-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_auto_20211123_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='historical_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6),
        ),
    ]
