# Generated by Django 3.2.9 on 2021-11-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_alter_deal_historical_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='historical_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=10.0, max_digits=6),
            preserve_default=False,
        ),
    ]
