# Generated by Django 3.2.9 on 2021-11-24 09:10

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0006_alter_deal_historical_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='product_img',
            field=models.URLField(default='https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deal',
            name='historical_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6),
        ),
    ]
