# Generated by Django 3.2.9 on 2021-11-24 09:18

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0007_auto_20211124_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='valid_till',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
