# Generated by Django 3.2.9 on 2021-11-25 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deals', '0008_alter_deal_valid_till'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='vote_down',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deal',
            name='vote_up',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deal',
            name='voter',
            field=models.ManyToManyField(blank=True, default=None, related_name='voter', to=settings.AUTH_USER_MODEL),
        ),
    ]
