# Generated by Django 3.2.9 on 2021-11-26 11:25

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0009_auto_20211126_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='promo_code',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
