# Generated by Django 3.2.9 on 2021-11-27 20:00

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0010_alter_deal_promo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
