# Generated by Django 3.2.10 on 2021-12-15 16:17

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0011_deal_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='current_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('USD', 'USD $'), ('PLN', 'zł')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='deal',
            name='delivery_cost_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('USD', 'USD $'), ('PLN', 'zł')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='deal',
            name='historical_price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('USD', 'USD $'), ('PLN', 'zł')], default='PLN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='deal',
            name='current_price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='PLN', max_digits=19),
        ),
        migrations.AlterField(
            model_name='deal',
            name='delivery_cost',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='PLN', max_digits=19),
        ),
        migrations.AlterField(
            model_name='deal',
            name='historical_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='PLN', max_digits=19),
        ),
    ]
