# Generated by Django 3.2.10 on 2021-12-16 11:30

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0012_auto_20211215_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='description',
            field=django_quill.fields.QuillField(max_length=5000),
        ),
    ]
