# Generated by Django 3.2.10 on 2021-12-17 10:34

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('deals', '0013_alter_deal_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='product_img',
            field=models.ImageField(upload_to='deals_photo'),
        ),
    ]
