# Generated by Django 3.2.10 on 2021-12-23 07:36

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0002_alter_product_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['-check_date']},
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='default', max_length=5000),
            preserve_default=False,
        ),
    ]
