# Generated by Django 3.2.10 on 2021-12-23 09:00

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0003_auto_20211223_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, unique=True),
        ),
    ]
