# Generated by Django 3.2.10 on 2021-12-23 10:40

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0005_auto_20211223_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, default='https://via.placeholder.com/150.jpg', null=True,
                                    upload_to='brands'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='https://via.placeholder.com/150.jpg', null=True,
                                    upload_to='products'),
        ),
    ]
