# Generated by Django 3.2.10 on 2021-12-23 11:27

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0006_auto_20211223_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, default='img.png', null=True, upload_to='brands'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='img.png', null=True, upload_to='products'),
        ),
    ]
