# Generated by Django 3.2.10 on 2021-12-24 10:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0007_auto_20211223_1227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['-brand']},
        ),
    ]
