# Generated by Django 3.2.10 on 2021-12-24 10:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0008_alter_brand_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['brand']},
        ),
    ]
