# Generated by Django 3.2.11 on 2022-01-04 14:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0009_alter_brand_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['brand']},
        ),
    ]
